changes in readme. Faulty for loop issue in forecasts list.
Most probably typo, but forecasts.text() must be forecasts.text()
-------- error ---------(for reference)
Traceback (most recent call last):
  File "something.py", line 'some-number', in <module>
    print(forecasts.text())
AttributeError: 'list' object has no attribute 'text' 
--------end of error message----------